version: "3.8"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: devcamper
    container_name: devcamper
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 3000:3000 
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - my_devcamper

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
    networks:
      - my_devcamper

volumes:
  mongo-db:

networks:
  my_devcamper:
    driver: bridge
