version: "3.8"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: devcamper
    container_name: devcamper
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "0.0.0.0:3000:3000" 
    volumes:
      - ./:/app
      - package_node-modules:/app/node_modules
    networks:
      my_devcamper:
        ipv4_address: 172.16.238.10

  mongo:
    image: mongo:4.4.21-rc0-focal
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      my_devcamper:
        ipv4_address: 172.16.238.11

volumes:
  mongo-db:
  package_node-modules:

networks:
  my_devcamper:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
